package com.kenstevens.stratinit.type;

public enum GameEventType {
	MOVE, BUILD_UNIT, BUILD_CITY, DISBAND, CEDE_UNIT, CEDE_CITY,
	SET_RELATION, CANCEL_MOVE, SWITCH_TERRAIN, CONCEDE, SEND_MESSAGE,
	TECH_UPDATE, GAME_START, GAME_END, CITY_CAPTURE, BATTLE,
	CITY_PRODUCTION, NUKE
}
